#spring:
#  h2:
#    console:
#      enabled: true#  mvc:#    view:#      prefix: /WEB-INF/
#      
#      suffix: .jsp
#      #    static-path-pattern: /resources/**
#      
#      
#server:#  port: 9192 
 
